<?php $Id$

/*
 * Implementation of hook_entity_info().
 */
function awesomerelationships_entity_info() {
  $return = array(
    'relationship' => array(
      'label' => t('Relationship'),
      'base table' => 'relationship',
      'fieldable' => FALSE,
      'entity keys' => array(
        'relationship_id' => 'relationship_id',
        'entity_type' => 'entity_type',
        'entity_id' => 'entity_id',
      ),
      'bundle keys' => array(
        'predicate' => 'predicate',
      ),
      'bundles' => array(
        // describe Drupal's built in relationships
        'creator' => array(
          'label' => t('Author'),
        ),
      ),
      'view modes' => array(),
    ),
  );
  return $return;
}

